[package]
name = "1brc_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.1"
memmap2 = "0.9.3"
memchr = "2.7.1"
